// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6c5Z-8N5JO3nMVwbtfP0TdUV6-6cjDbc',
    appId: '1:322517167973:web:c2088f11ec3979c62cfb8c',
    messagingSenderId: '322517167973',
    projectId: 'workouttrackerapp-bf39e',
    authDomain: 'workouttrackerapp-bf39e.firebaseapp.com',
    storageBucket: 'workouttrackerapp-bf39e.firebasestorage.app',
    measurementId: 'G-C5RNH6BELM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO99G5xSumKtD2hywRimz2I-y3-Mck5tA',
    appId: '1:322517167973:android:9530f4287722ef332cfb8c',
    messagingSenderId: '322517167973',
    projectId: 'workouttrackerapp-bf39e',
    storageBucket: 'workouttrackerapp-bf39e.firebasestorage.app',
  );
}
