// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrj8r2TbC-oShshHXb56B6fTx2IsGW1qI',
    appId: '1:165444819442:web:d74dd83419d573d095736b',
    messagingSenderId: '165444819442',
    projectId: 'myfluttercrud-a79e7',
    authDomain: 'myfluttercrud-a79e7.firebaseapp.com',
    storageBucket: 'myfluttercrud-a79e7.firebasestorage.app',
    measurementId: 'G-1X5GN3DGMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2vPbF0S2nzcw8H9gTTPGLZoy0SbGsxtE',
    appId: '1:165444819442:android:757fc8c26827de8e95736b',
    messagingSenderId: '165444819442',
    projectId: 'myfluttercrud-a79e7',
    storageBucket: 'myfluttercrud-a79e7.firebasestorage.app',
  );
}
